inputs:
  - id: some_emails
    type: list

  - id: redis_notifications
    type: redis_streams
    host: redis-server
    port: 6379
    stream_name: notifications_stream
    consumer_group: notification_processors
    consumer_name: worker_1
    start_id: "0"

jobs:
  - id: hello_world_printer_job
    type: espresso_job
    module: testing.test
    function: print_hello_world
    schedule:
      kind: cron
      cron: "0 9 * * *"      # every day at 09:00
    max_retries: 3
    retry_delay_seconds: 60

  - id: iterator_job
    type: espresso_job
    module: testing.test
    function: loop_n_times
    args:
      - 15
    schedule:
      kind: interval
      every_seconds: 15     # every 15 seconds

  - id: send_welcome_emails_job
    type: espresso_job
    module: testing.test
    function: send_welcome_email
    trigger:
      kind: input
      input_id: some_emails
    schedule:
      kind: on_demand
    max_retries: 4
    retry_delay_seconds: 90
    batch_size: 10

  - id: process_redis_notifications_job
    type: espresso_job
    module: testing.test
    function: process_notification
    trigger:
      kind: input
      input_id: redis_notifications
    schedule:
      kind: interval
      every_seconds: 5
    max_retries: 3
    retry_delay_seconds: 30
    batch_size: 5