from typing import Protocol, Any, List, Tuple, Optional


class EspressoInputAdapter(Protocol):
    async def poll(self) -> Any: ...

    async def poll_all(self) -> List[Any]: ...

    async def poll_batch(self, batch_size: int) -> Tuple[List[Any], Optional[str]]: ...

    async def has_data(self) -> bool: ...
