from typing import Protocol, Any, List, Tuple, Optional


class EspressoInputAdapter(Protocol):
    def poll(self) -> Any: ...

    def poll_all(self) -> List[Any]: ...

    def poll_batch(self, batch_size: int) -> Tuple[List[Any], Optional[str]]: ...

    def has_data(self) -> bool: ...
